// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversitySystem.Infrastructure;

#nullable disable

namespace UniversitySystem.Infrastructure.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KursKurs", b =>
                {
                    b.Property<int>("WymaganePrzezId")
                        .HasColumnType("int");

                    b.Property<int>("WymaganiaId")
                        .HasColumnType("int");

                    b.HasKey("WymaganePrzezId", "WymaganiaId");

                    b.HasIndex("WymaganiaId");

                    b.ToTable("WymaganiaKursow", (string)null);
                });

            modelBuilder.Entity("UniversitySystem.Domain.Gabinet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Budynek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerPokoju")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId")
                        .IsUnique();

                    b.ToTable("Gabinety");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KodKursu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PunktyECTS")
                        .HasColumnType("int");

                    b.Property<int>("WydzialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WydzialId");

                    b.ToTable("Kursy");
                });

            modelBuilder.Entity("UniversitySystem.Domain.LicznikIndeksow", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("AktualnaWartosc")
                        .HasColumnType("int");

                    b.HasKey("Prefix");

                    b.ToTable("LicznikiIndeksow");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndeksUczelniany")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TytulNaukowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndeksUczelniany")
                        .IsUnique();

                    b.ToTable("Profesorowie");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndeksUczelniany")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RokStudiow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndeksUczelniany")
                        .IsUnique();

                    b.ToTable("Studenci");

                    b.HasDiscriminator().HasValue("Student");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UniversitySystem.Domain.Wydzial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wydzialy");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Zapis", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<double?>("Ocena")
                        .HasColumnType("float");

                    b.Property<int>("Semestr")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "KursId");

                    b.HasIndex("KursId");

                    b.ToTable("Zapisy");
                });

            modelBuilder.Entity("UniversitySystem.Domain.StudentStudiowMagisterskich", b =>
                {
                    b.HasBaseType("UniversitySystem.Domain.Student");

                    b.Property<int?>("PromotorId")
                        .HasColumnType("int");

                    b.Property<string>("TematPracyDyplomowej")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("PromotorId");

                    b.HasDiscriminator().HasValue("StudentStudiowMagisterskich");
                });

            modelBuilder.Entity("KursKurs", b =>
                {
                    b.HasOne("UniversitySystem.Domain.Kurs", null)
                        .WithMany()
                        .HasForeignKey("WymaganePrzezId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitySystem.Domain.Kurs", null)
                        .WithMany()
                        .HasForeignKey("WymaganiaId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniversitySystem.Domain.Gabinet", b =>
                {
                    b.HasOne("UniversitySystem.Domain.Profesor", "Profesor")
                        .WithOne("Gabinet")
                        .HasForeignKey("UniversitySystem.Domain.Gabinet", "ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Kurs", b =>
                {
                    b.HasOne("UniversitySystem.Domain.Wydzial", "Wydzial")
                        .WithMany("Kursy")
                        .HasForeignKey("WydzialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wydzial");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Profesor", b =>
                {
                    b.OwnsOne("UniversitySystem.Domain.Adres", "AdresZamieszkania", b1 =>
                        {
                            b1.Property<int>("ProfesorId")
                                .HasColumnType("int");

                            b1.Property<string>("KodPocztowy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Miasto")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ulica")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProfesorId");

                            b1.ToTable("Profesorowie");

                            b1.WithOwner()
                                .HasForeignKey("ProfesorId");
                        });

                    b.Navigation("AdresZamieszkania")
                        .IsRequired();
                });

            modelBuilder.Entity("UniversitySystem.Domain.Student", b =>
                {
                    b.OwnsOne("UniversitySystem.Domain.Adres", "AdresZamieszkania", b1 =>
                        {
                            b1.Property<int>("StudentId")
                                .HasColumnType("int");

                            b1.Property<string>("KodPocztowy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Miasto")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ulica")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentId");

                            b1.ToTable("Studenci");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("AdresZamieszkania")
                        .IsRequired();
                });

            modelBuilder.Entity("UniversitySystem.Domain.Zapis", b =>
                {
                    b.HasOne("UniversitySystem.Domain.Kurs", "Kurs")
                        .WithMany("Zapisy")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitySystem.Domain.Student", "Student")
                        .WithMany("Zapisy")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversitySystem.Domain.StudentStudiowMagisterskich", b =>
                {
                    b.HasOne("UniversitySystem.Domain.Profesor", "Promotor")
                        .WithMany("Seminarzysci")
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Promotor");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Kurs", b =>
                {
                    b.Navigation("Zapisy");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Profesor", b =>
                {
                    b.Navigation("Gabinet");

                    b.Navigation("Seminarzysci");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Student", b =>
                {
                    b.Navigation("Zapisy");
                });

            modelBuilder.Entity("UniversitySystem.Domain.Wydzial", b =>
                {
                    b.Navigation("Kursy");
                });
#pragma warning restore 612, 618
        }
    }
}
